# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0d759a75b66e5076782eacde872da18b"
application_url = "https://shopify-print-product-sheet.onrender.com/"
embedded = true
name = "Print product sheet"
handle = "buero-print-product-sheet"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopify-print-product-sheet.onrender.com/auth/callback",
  "https://shopify-print-product-sheet.onrender.com/auth/shopify/callback",
  "https://shopify-print-product-sheet.onrender.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "spicca-academy.myshopify.com"
include_config_on_deploy = true
automatically_update_urls_on_dev = true
